#!/usr/bin/env bash
#  ____ _____
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/
# |____/ |_|
#
# A customized sxhkdrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

### WM INDEPENDENT KEYBINDINGS ###

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd
super + shift + s
    flameshot gui

XF86AudioPlay
    /home/j/.config/sxhkd/play-pause.sh
XF86AudioNext
    /home/j/.config/sxhkd/skip.sh
XF86AudioPrev
    /home/j/.config/sxhkd/back.sh
XF86AudioRaiseVolume
    pactl set-sink-volume 1 +5%
XF86AudioLowerVolume
    pactl set-sink-volume 1 -5%
XF86AudioMute
    pactl set-sink-mute 1 toggle
